name: cross_wallpaper
description: A new flutter plugin project.
version: 0.0.1
author: Phani Rithvij (phanirithvij20003@gmail.com)
homepage: https://github.com/phanirithvij/cross-wallpaper

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^0.1.3-dev.3
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.rithvij.cross_wallpaper
    pluginClass: CrossWallpaperPlugin
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
